### ISSUE TITLE
Setup database design (ERD)

### ISSUE THREAD

**Issue by KixPanganiban** [StopClickBait/SCB-Backend#2]

**Comment by BrandonDenton** [comment]
What elements will this database need to organize (posts, user info, etc)?

**Comment by le3bl** [comment]
Articles
Users
UserArticles
UserArticleAnswers
UserArticleAnswerVotes
Roles
UserRoles
Tags/Categories
ArticleTags/Categories

**Comment by BrandonDenton** [comment]
I've submitted a pull request for edits to db.js, which will build the general layout of the database. Let me know if there are other suggestions you would provide before I complete that implementation over the next day.

**Comment by le3bl** [comment]
BrandonDenton, check out my comments on the Pull Request you created. I don't think either of us have the time required to complete the task today, but with our powers combined...

**Comment by BrandonDenton** [comment]
Great, thanks for the feedback. Made a different pull request and am editing my work for Laravel conversion.
